backend:
  name: github
  repo: CDLBuddy/fishing-lure-site
  branch: main
  base_url: https://fishing-lure-site.vercel.app
  auth_endpoint: /api/auth

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

publish_mode: editorial_workflow

editor:
  preview: true

preview_styles:
  - /styles/tokens.css
  - /styles/base.css
  - /admin/preview.css

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"

# ----------------- GALLERY (CATCHES) -----------------
collections:
  - label: "Gallery (Catches)"
    name: "catches"
    label_singular: "Catch Photo"
    folder: "content/catches"
    create: true
    identifier_field: "id"

    # Compact, predictable filenames
    slug: "ct-{{year}}{{month}}{{day}}-{{slug}}"
    extension: "json"
    format: "json"

    summary: "{{title}} • {{angler}} • {{species}}"
    sortable_fields: ["title","angler","date","featured","publishedAt","sort"]
    view_filters:
      - { label: "Featured Only", field: featured, pattern: true }
      - { label: "Published", field: status, pattern: "published" }

    fields:
      # Keep ID short + stable; default generated from current slug
      - label: "ID (auto)"
        name: "id"
        widget: "string"
        required: false
        default: "{{slug}}"
        hint: "Lowercase letters, numbers, hyphens only"
        pattern: ["^[a-z0-9-]{2,40}$", "Use 2–40 chars: a–z, 0–9, -"]

      - { label: "Photo Title/Caption", name: "title", widget: "string" }

      - label: "When was it caught?"
        name: "date"
        widget: "datetime"
        required: false
        date_format: "MM/DD/YYYY"
        time_format: false

      - { label: "Angler Name", name: "angler", widget: "string", required: false }

      - label: "Fish Species"
        name: "species"
        widget: "select"
        required: false
        options:
          - "Largemouth Bass"
          - "Smallmouth Bass"
          - "Spotted Bass"
          - "Striped Bass"
          - "Pike"
          - "Muskie"
          - "Walleye"
          - "Crappie"
          - "Bluegill"
          - "Trout"
          - "Catfish"
          - "Redfish"
          - "Snook"
          - "Tarpon"
          - "Other"

      - { label: "Location", name: "location", widget: "string", required: false }

      - label: "Length (inches)"
        name: "lengthIn"
        widget: "number"
        required: false
        min: 0
        max: 100
        step: 0.5
        value_type: "float"

      - label: "Weight (pounds)"
        name: "weightLb"
        widget: "number"
        required: false
        min: 0
        max: 100
        step: 0.1
        value_type: "float"

      - label: "Which Lure Was Used?"
        name: "lureId"
        widget: "relation"
        collection: "products"
        search_fields: ["name","id","category"]
        value_field: "id"
        display_fields: ["name","category"]
        required: false

      # Minimal, flat list for images (no deep objects)
      - label: "Photos"
        name: "images"
        widget: "list"
        collapsed: false
        summary: "{{fields.alt}}"
        hint: "Upload 1–5 photos"
        fields:
          - { label: "Photo", name: "src", widget: "image" }
          - { label: "Description", name: "alt", widget: "string", required: false }
          - { label: "Width (px)", name: "width", widget: "number", required: false, min: 1 }
          - { label: "Height (px)", name: "height", widget: "number", required: false, min: 1 }

      - { label: "Tags", name: "tags", widget: "list", required: false }

      - { label: "Featured", name: "featured", widget: "boolean", default: false, required: false }

      - label: "Status"
        name: "status"
        widget: "select"
        options: [{ label: "Draft", value: "draft" }, { label: "Published", value: "published" }]
        default: "draft"

      - { label: "Sort Order", name: "sort", widget: "number", required: false }

      - { label: "Publish Date", name: "publishedAt", widget: "datetime", required: false }

  # ----------------- PRODUCTS -----------------
  - label: "Products (Lures)"
    name: "products"
    label_singular: "Product"
    folder: "content/products"
    create: true
    identifier_field: "id"

    # Keep product filenames short & stable
    slug: "p-{{slug}}"
    extension: "json"
    format: "json"

    summary: "{{name}} • {{category}}"
    sortable_fields: ["name","category","featured","publishedAt","sort"]
    view_filters:
      - { label: "Featured Only", field: featured, pattern: true }
      - { label: "Active Products", field: status, pattern: "active" }

    fields:
      - label: "Product ID"
        name: "id"
        widget: "string"
        hint: "Short code (e.g., sb-001, crank-blue)"
        pattern: ["^[a-z0-9-]{2,40}$", "Use 2–40 chars: a–z, 0–9, -"]

      - { label: "Product Name", name: "name", widget: "string", hint: "e.g., River Shimmer Spinnerbait" }

      - label: "Description"
        name: "description"
        widget: "text"
        hint: "Describe the lure, how it works, best conditions"
        pattern: ["^.{20,}$", "Please write at least 20 characters"]

      - label: "Category"
        name: "category"
        widget: "select"
        options:
          - { label: "Spinnerbait", value: "spinnerbait" }
          - { label: "Jig", value: "jig" }
          - { label: "Crankbait", value: "crankbait" }
          - { label: "Topwater", value: "topwater" }
          - { label: "Soft Plastic", value: "soft-plastic" }

      - label: "Product Photos"
        name: "images"
        widget: "list"
        collapsed: false
        summary: "Photo {{index}}"
        hint: "Upload 1–5 product photos"
        field:
          label: "Image"
          name: "src"
          widget: "image"

      - label: "Variants (Sizes/Colors/Weights)"
        name: "variants"
        widget: "list"
        collapsed: false
        summary: "{{fields.label}} • ${{fields.price}}"
        hint: "Add different options"
        fields:
          - label: "Variant ID"
            name: "id"
            widget: "string"
            hint: "Internal code (e.g., v1, 3-8oz-chart)"
            pattern: ["^[a-z0-9-]{1,30}$", "Use 1–30 chars: a–z, 0–9, -"]

          # Use select, but allow custom values
          - label: "Variant Label"
            name: "label"
            widget: "select"
            options:
              - "1/8 oz"
              - "1/4 oz"
              - "3/8 oz"
              - "1/2 oz"
              - "3/4 oz"
              - "1 oz"
              - "Chartreuse"
              - "White"
              - "Black"
              - "Blue"
              - "Silver"
              - "Gold"
              - "Red"
              - "Green"
              - "Purple"
              - "Brown/Orange"
              - "Natural Shad"
              - "Fire Tiger"
              - "1/8 oz • Chartreuse"
              - "1/4 oz • Chartreuse"
              - "3/8 oz • Chartreuse"
              - "1/2 oz • Chartreuse"
              - "1/8 oz • White"
              - "1/4 oz • White"
              - "3/8 oz • White"
              - "1/2 oz • White"
              - "Custom"
            allow_add: true
            hint: "Pick or type a custom label (e.g., 1/2 oz • Smoke/Blue)"

          - { label: "SKU", name: "sku", widget: "string", hint: "Your inventory code" }

          - label: "Price (USD)"
            name: "price"
            widget: "number"
            required: false
            min: 0
            step: 0.01
            value_type: "float"
            hint: "Display price only (no currency symbol). Example: 12.99"

          - { label: "Stripe Price ID", name: "stripePriceId", widget: "string", required: false, hint: "Leave blank until checkout enabled" }

      - { label: "Tags", name: "tags", widget: "list", required: false, hint: "Keywords for search/filtering" }

      - { label: "Featured", name: "featured", widget: "boolean", default: false, required: false }

      - label: "Status"
        name: "status"
        widget: "select"
        options:
          - { label: "Draft", value: "draft" }
          - { label: "Active", value: "active" }
          - { label: "Hidden", value: "hidden" }
        default: "draft"
        required: false

      - { label: "Sort Order", name: "sort", widget: "number", required: false }

      - { label: "Publish Date", name: "publishedAt", widget: "datetime", required: false }